### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HyperBeats** [zZan54/BananaDropFarm#1]
hello i have this error 

```
C:\Program Files (x86)\Steam\steamapps\common\Banana>python menu.py
Traceback (most recent call last):
  File "menu.py", line 14, in <module>
    gameModule = module_from_name(pm.process_handle, "GameAssembly.dll").lpBaseOfDll
AttributeError: 'NoneType' object has no attribute 'lpBaseOfDll'

C:\Program Files (x86)\Steam\steamapps\common\Banana>
```

**Comment by zaklonodkida** [comment]
i got the same error because my game was not running

**Comment by zZan54** [comment]
Thanks for bringing this up, make sure to have the game open before launching the menu.

**Comment by HyperBeats** [comment]
the game is open

**Comment by HyperBeats** [comment]
![image](https://github.com/zZan54/BananaDropFarm/assets/45314346/1e96618e-5c3c-4a85-b231-97ba77569c38)

**Comment by HyperBeats** [comment]
i go try

**Comment by HyperBeats** [comment]
I've just reinstalled but still the same error
![image](https://github.com/zZan54/BananaDropFarm/assets/45314346/73eb4780-ef24-4edb-9834-0f8ba79377a0)

**Comment by HyperBeats** [comment]
ok its work in my computer but not in my vps
