### ISSUE TITLE
Error while using --noconsole on compiling

### ISSUE THREAD

**Issue by LuckyNooan** [zZan54/BananaDropFarm#10]
I used --noconsole while compiling and got this error:

![image](https://github.com/user-attachments/assets/22581083-4eb0-43d5-bf81-0ff2d73190d6)

Any fixes?

**Comment by zZan54** [comment]
Hmm... I didn't notice this issue. I'll look into it and fix it. Thanks for pointing it out!

**Comment by LuckyNooan** [comment]
Thank you, @zZan54! The fix works perfectly now.
