### ISSUE TITLE
Not an issue but something to think about.

### ISSUE THREAD

**Issue by Dethkiller15** [zZan54/BananaDropFarm#14]
Why not make it a docker container? You shouldn't need to run a VNC if you don't want to and run it through a web panel or just a config file, and if you did use a VNC it should be a 1 time setup in the code and DONE. That way you can run it on something like a raspberry Pi(or 100% in the background on a users PC) and have it be more power efficient.

It may be a bit confusing at first but after you have it set up you can just focus on the actual script code after that.

I suggest you look at linuxserver's work as if you use VNC PLEASE use KasmVNC as it has easy to configure security.

Oh and if you do it this way then the user doesn't have to be signed out of steam on their computer with this method.(it would also be easier to reproduce user issues because hardware/software should be exactly the same to the container.)

**Comment by zZan54** [comment]
Thank you for your suggestion. Currently, containerizing isn't planned as I don't have much experience with Docker containters. However, I'll keep this in mind for future updates.
