### ISSUE TITLE
example config to not going banned while using it on a server

### ISSUE THREAD

**Issue by geeflaxx** [zZan54/BananaDropFarm#15]
hi,
which could be the best config for a 24h server?

thanks for this tool

**Comment by zZan54** [comment]
Hi @geeflaxx,
Thanks for your interest in BananaDropFarm. I'd like to clarify a few points regarding your question:

1. The game currently does not have an anti-cheat system, so you don't need to worry about getting banned while using this tool on a server.
2. As for the best configuration for a 24/7 server, the example config that comes with BananaDropFarm is already well-optimized for continuous use. It provides a good balance of efficiency and safety.

If you haven't already, I recommend starting with the provided example config and adjusting it based on your specific needs.
