### ISSUE TITLE
Dunno if this is nothin or not. Not looking for ridicule, just knowledge.

### ISSUE THREAD

**Issue by Haxnstuff** [zZan54/BananaDropFarm#3]
https://www.virustotal.com/gui/file/c029b0dd4e7e90f8bf32fa101acb20b4f5ff00ca4d9020f1c365d42f3e527860?nocache=1

![Screenshot 2024-06-17 141503](https://github.com/zZan54/BananaDropFarm/assets/76791182/b350b17d-a304-4b1d-8289-fce692124424)

**Comment by zZan54** [comment]
Getting those antivirus flags when using PyInstaller is pretty common, so no need to worry too much about it. That's why I just provide the script itself instead of a pre-built executable.
